import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@ui5/webcomponents-react";
import { ContextProvider } from "./context/context";

import "./globals.css";
import { Header } from "./ui/common/index";
import { Menu } from "./ui/menu/index";
import { Alert } from "./ui/alert";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#d9d9d9]`}
        >
          <ContextProvider>
            <Menu />
            <Header />
            {children}
            {/* <Alert alert={}/> */}
          </ContextProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
